name: Publish snapshots to maven

on:
  push:
    branches:
      - main

jobs:
  build-and-publish-snapshots:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Load secret
        uses: 1password/load-secrets-action@v2
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          SONATYPE_USERNAME: op://opensearch-infra-secrets/maven-central-portal-credentials/username
          SONATYPE_PASSWORD: op://opensearch-infra-secrets/maven-central-portal-credentials/password
      - name: publish snapshots to Apache Maven repositories
        run: |
          ./gradlew --no-daemon publishPublishMavenPublicationToSnapshotsRepository
